import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'
import { ClerkProvider } from '@clerk/nextjs'
import { ModalProvider } from '@/providers/modal-provider'
import prismadb from '@/lib/prismadb'
import { ToasterProvier } from '@/providers/toast-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Store Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  prismadb.store.create({
    data: {
      name: "ဆာတယ်",
      userId: "2332dfdfa"
    }
  })
  return (
   
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ToasterProvier />
          <ModalProvider />
            {children}
      </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  )
}
